# Generated by Django 2.0.8 on 2018-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='cscs_card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='cscs_card_url',
            field=models.URLField(null=True),
        ),
    ]
