# Generated by Django 2.0.8 on 2018-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181020_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.TextField(default='XX99 XX99', max_length=9),
        ),
    ]
