# Generated by Django 2.0.8 on 2018-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181020_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rate',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
